export default[
    {
        "subject":"SPE",
        "number":2,
        "elligibility":"mtech",
        "requirement":"devops",
        "deadline":"3-7-23"
    },
    {
        "subject":"ML",
        "number":2,
        "elligibility":"mtech",
        "requirement":"NLP",
        "deadline":"3-7-23"
    },
    {
        "subject":"SS",
        "number":2,
        "elligibility":"mtech",
        "requirement":"devops",
        "deadline":"3-7-23"
    },
    {
        "subject":"SS",
        "number":2,
        "elligibility":"mtech",
        "requirement":"devops",
        "deadline":"3-7-23"
    }
]